/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/brainstorming`; params?: Router.UnknownInputParams; } | { pathname: `/daily-goals`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/linked-notes`; params?: Router.UnknownInputParams; } | { pathname: `/notes`; params?: Router.UnknownInputParams; } | { pathname: `/pomodoro`; params?: Router.UnknownInputParams; } | { pathname: `/progress-chart`; params?: Router.UnknownInputParams; } | { pathname: `/projects`; params?: Router.UnknownInputParams; } | { pathname: `/reports`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/timer`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-planner`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useStorage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/brainstorming`; params?: Router.UnknownOutputParams; } | { pathname: `/daily-goals`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/linked-notes`; params?: Router.UnknownOutputParams; } | { pathname: `/notes`; params?: Router.UnknownOutputParams; } | { pathname: `/pomodoro`; params?: Router.UnknownOutputParams; } | { pathname: `/progress-chart`; params?: Router.UnknownOutputParams; } | { pathname: `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/timer`; params?: Router.UnknownOutputParams; } | { pathname: `/weekly-planner`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useStorage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/brainstorming${`?${string}` | `#${string}` | ''}` | `/daily-goals${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/linked-notes${`?${string}` | `#${string}` | ''}` | `/notes${`?${string}` | `#${string}` | ''}` | `/pomodoro${`?${string}` | `#${string}` | ''}` | `/progress-chart${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `/timer${`?${string}` | `#${string}` | ''}` | `/weekly-planner${`?${string}` | `#${string}` | ''}` | `/../hooks/useStorage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/brainstorming`; params?: Router.UnknownInputParams; } | { pathname: `/daily-goals`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/linked-notes`; params?: Router.UnknownInputParams; } | { pathname: `/notes`; params?: Router.UnknownInputParams; } | { pathname: `/pomodoro`; params?: Router.UnknownInputParams; } | { pathname: `/progress-chart`; params?: Router.UnknownInputParams; } | { pathname: `/projects`; params?: Router.UnknownInputParams; } | { pathname: `/reports`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/timer`; params?: Router.UnknownInputParams; } | { pathname: `/weekly-planner`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useStorage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
